FROM python:slim as BUILDER
RUN apt-get update && apt-get install -y gcc && \
    pip install --upgrade pip && \
    python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
ADD ./requirements.txt /tmp/requirements.txt
RUN pip install -qr /tmp/requirements.txt
USER 1001
EXPOSE 8080
CMD ["python", "app.py"]
